apiVersion: batch/v1
kind: Job
metadata:
  name: pgbench-init-high-no-encryption-repl1
  namespace: portworx
spec:
  template:
    metadata:
      labels:
        app: pgbench-init-high-no-encryption-repl1
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
      - name: postgres
        image: postgres:9.5
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: pgbench
        - name: PGUSER
          value: pgbench
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: password.txt
        - name: PGBENCH_PASSWORD
          value: superpostgres
        command: ["/bin/sh"]
        args: ["-c",  "export PGPASSWORD=$POSTGRES_PASSWORD; psql -h psql-high-no-encryption-repl1 -p $PSQL_HIGH_NO_ENCRYPTION_REPL1_SERVICE_PORT -U $POSTGRES_USER -c 'create database pxdemo;'; pgbench -h psql-high-no-encryption-repl1 -p $PSQL_HIGH_NO_ENCRYPTION_REPL1_SERVICE_PORT -U $POSTGRES_USER -i -s 50 pxdemo"]
      restartPolicy: Never
