kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: JOB_NAME
spec:
  storageClassName: px-repl1-sc
  # storageClassName: gp2
  # storageClassName: local-storage
  # storageClassName: ibmc-block-bronze
  # storageClassName: ibmc-block-silver
  # storageClassName: ibmc-block-gold
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: JOB_NAME
spec:
  template:
    spec:
      schedulerName: stork
      initContainers:
      - name: dbench-init
        image: dmonakhov/alpine-fio
        imagePullPolicy: Always
        args:
        - "fio"
        - "--blocksize=64k"
        - "--filename=/data/fiotest"
        - "--ioengine=libaio"
        - "--readwrite=write"
        - "--size=4G"
        - "--name=write"
        - "--direct=1"
        - "--iodepth=128"
        - "--end_fsync=1"
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      containers:
      - name: dbench
        image: fmrtl73/dbench:0.11
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
          # - name: DBENCH_QUICK
          #   value: "yes"
          # - name: FIO_SIZE
          #   value: 1G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          - name: FIO_DIRECT
            value: "0"
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: JOB_NAME
      imagePullSecrets:
      - name: regcred
  backoffLimit: 4
