apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-rs-mongo-node-0
  name: mongo-rs-mongo-node-0
  namespace: mongo-rs
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: db-port
    nodePort: 31339
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongo-rs-mongo-node-0
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-rs-mongo-node-1
  name: mongo-rs-mongo-node-1
  namespace: mongo-rs
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: db-port
    nodePort: 30067
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongo-rs-mongo-node-1
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-rs-mongo-node-2
  name: mongo-rs-mongo-node-2
  namespace: mongo-rs
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: db-port
    nodePort: 31612
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongo-rs-mongo-node-2
  sessionAffinity: None
  type: NodePort


