apiVersion: batch/v1
kind: Job
metadata:
  name: fio-read-SC_NAME-job
  namespace: portworx
spec:
  template:
    spec:
      schedulerName: stork
      securityContext:
        runAsUser: 1000 
        fsGroup: 2000
        runAsNonRoot: true
      containers:
      - name: fio-read
        image: dmonakhov/alpine-fio
        volumeMounts:
        - mountPath: /mnt
          name: test-volume
        args:
          - "fio"
          - "--blocksize=64k"
          - "--filename=/mnt/fio.dat"
          - "--ioengine=libaio"
          - "--readwrite=read"
          - "--size=10G"
          - "--name=test"
          - "--direct=1"
          - "--iodepth=128"
          - "--readonly"
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: SC_NAME-pvc
